title: "QRCode PIX Java" 
description: "Biblioteca Java 17+ para geração de QRCode PIX Copia e Cola"
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
encoding: utf-8
  
exclude:
  - CONTRIBUTING.md
  - .github
  - .gitignore

plugins:
  - jekyll-mentions
  - jemoji

webrick:
  headers:
    keywords: "java,api,qrcode,payment,lib,banking,jdk,pagamentos,cobranca,pix,automacao,banco-central-do-brasil,bcb,pix-copia-e-cola"
